name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build
        env:
          scheme: "Yahtzee"
          platform: "iOS Simulator"
          device: "iPhone 16"
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -project "Yahtzee.xcodeproj" -destination "platform=$platform,name=$device"
          
      - name: Test
        env:
          scheme: "Yahtzee"
          platform: "iOS Simulator"
          device: "iPhone 16"
        run: |
          xcodebuild test-without-building -scheme "$scheme" -project "Yahtzee.xcodeproj" -parallel-testing-enabled NO -destination "platform=$platform,name=$device"
